In [14]:
import pandas as pd
a=pd.read_csv("/content/train.csv")
print(a)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7
1       0.7        136        3  ...        905      1988  2631    17     3
2       0.9        145        5  ...       1263      1716  2603    11     2
3       0.8        131        6  ...       1216      1786  2769    16     8
4       0.6        141        2  ...       1208      1212  1411     8     2
...     ...        ...      ...  ...        ...       ...   ...   ...   ...
1995    0.8        106        6  ...       1222      1890   668    13     4
1996    0.2        187        4  ...        915      1965  2032    11    10
1997    0.7        108        8  ...        868      1632  3057     9     1
1998    0.1        145        5  ...        336       670   869    18    10
1999    0.9        168        6  ...        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi  price_range
0            19        0             0     1            1
1             7        1             1     0            2
2             9        1             1     0            2
3            11        1             0     0            2
4            15        1             1     0            1
...         ...      ...           ...   ...          ...
1995         19        1             1     0            0
1996         16        1             1     1            2
1997          5        1             1     0            3
1998         19        1             1     1            0
1999          2        1             1     1            3

[2000 rows x 21 columns]

In [15]:


x=a.drop("price_range",axis=1)
print(x)
y=a["price_range"]
print(y)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7
1       0.7        136        3   6        905      1988  2631    17     3
2       0.9        145        5   6       1263      1716  2603    11     2
3       0.8        131        6   9       1216      1786  2769    16     8
4       0.6        141        2  14       1208      1212  1411     8     2
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1995    0.8        106        6  14       1222      1890   668    13     4
1996    0.2        187        4   3        915      1965  2032    11    10
1997    0.7        108        8   3        868      1632  3057     9     1
1998    0.1        145        5   5        336       670   869    18    10
1999    0.9        168        6  16        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi
0            19        0             0     1
1             7        1             1     0
2             9        1             1     0
3            11        1             0     0
4            15        1             1     0
...         ...      ...           ...   ...
1995         19        1             1     0
1996         16        1             1     1
1997          5        1             1     0
1998         19        1             1     1
1999          2        1             1     1

[2000 rows x 20 columns]
0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x)
x_scaled=scaler.transform(x)
print(x_scaled)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]

In [16]:
from sklearn.model_selection import train_test_split
x_scaled_train, x_scaled_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=34)
print(" x train is",x_scaled_train)
print("x test is",x_scaled_test)
print("y train is",y_train)
print("y test is",y_test)

 x train is       battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
547            1117     1          0.6         1   0       0          31
721             808     0          0.5         1   0       0           8
872             569     1          0.5         1  10       1           4
439            1469     0          2.1         0   0       0           8
1792           1777     0          2.2         1   0       0          15
...             ...   ...          ...       ...  ..     ...         ...
1782           1436     1          2.4         1   3       1          23
1897           1075     0          0.5         1   2       0          11
490             685     0          2.7         0   7       0          17
1146           1923     0          1.0         1   5       1          14
1441            599     1          2.9         0   0       1          64

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
547     0.2        146        2   7       1258      1627  2003     8     7
721     0.1        192        4   1        618      1891  3762    15     9
872     0.8        170        3  19        351      1159  2351     8     7
439     0.7        123        7   0        398      1133  1052     8     1
1792    0.2        100        4   7        553       874  1552    10     8
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1782    0.3        106        5   4        189      1411  2488     8     4
1897    0.2        122        1  16        271      1769  3927     8     3
490     0.3        174        6  20        725       870  1223     8     0
1146    0.9        154        4   6         15       525  2519    13     0
1441    0.3        186        8   1        103       646  3396     5     3

      talk_time  three_g  touch_screen  wifi
547          14        0             1     1
721          12        1             0     1
872          10        1             1     0
439           3        0             1     0
1792         10        1             1     0
...         ...      ...           ...   ...
1782          8        1             0     0
1897          7        1             0     0
490          18        1             0     1
1146         16        1             0     1
1441          7        1             0     0

[1600 rows x 20 columns]
x test is       battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1312           1142     1          1.1         0   0       1           6
479            1589     1          2.2         1   2       0          58
1404           1447     0          0.5         0   3       0          40
664             914     1          0.5         0   0       1          26
1133           1528     1          1.8         1   3       1          55
...             ...   ...          ...       ...  ..     ...         ...
1891           1367     0          2.9         0   4       0          56
217            1336     0          0.9         0   5       1          17
286             612     1          1.9         1   6       0          16
1380           1811     0          2.9         0   0       0          33
130            1414     0          2.0         1   2       0          54

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
1312    0.5        198        4   0        739      1766  1273    19     0
479     0.1        128        4   4        957      1911  3961    16    14
1404    0.7        184        2   5        963      1062   471     8     4
664     0.7        147        4   0        706       721  1122    12     9
1133    0.8        129        5   6        454      1762  1282    11     9
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1891    0.8        176        2   6         36       642   299     6     2
217     0.2        194        5   9         55       583  1869    13     1
286     0.3        102        7   7       1360      1891  3161     8     4
1380    0.2        132        8   2       1099      1553  2610     8     3
130     0.8         99        7   3        262       829  3799    17     7

      talk_time  three_g  touch_screen  wifi
1312          6        1             0     0
479          14        1             0     1
1404         20        0             0     1
664           2        1             1     1
1133         11        1             1     1
...         ...      ...           ...   ...
1891         10        0             1     0
217          16        1             1     1
286           3        0             0     0
1380         13        1             1     0
130           7        1             0     1

[400 rows x 20 columns]
y train is 547     2
721     3
872     1
439     0
1792    1
       ..
1782    2
1897    3
490     0
1146    2
1441    2
Name: price_range, Length: 1600, dtype: int64
y test is 1312    1
479     3
1404    0
664     0
1133    1
       ..
1891    0
217     1
286     3
1380    3
130     3
Name: price_range, Length: 400, dtype: int64

In [20]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
a=pd.read_csv('/content/heart.csv')
x = a.drop("target", axis=1)
y= a["target"]
print(x)
print(y)
scaler = MinMaxScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)
print(x_scaled)
x_scaled_train, x_scaled_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.5, random_state=45)
print(x_scaled_train)
print(y_train)
print(x_scaled_test)
print(y_test)
c=a.columns
print(c)
for i in c:
  print(a[i])

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]
0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64
[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]
[[0.35416667 0.         0.         ... 0.5        0.         0.66666667]
 [0.4375     1.         0.66666667 ... 0.5        0.25       1.        ]
 [0.52083333 1.         0.66666667 ... 1.         0.         1.        ]
 ...
 [0.5        1.         0.         ... 1.         0.         1.        ]
 [0.3125     1.         0.33333333 ... 1.         0.         0.66666667]
 [0.41666667 0.         0.33333333 ... 0.5        0.         0.66666667]]
119    1
188    0
37     1
261    0
82     1
      ..
163    1
213    0
95     1
32     1
131    1
Name: target, Length: 151, dtype: int64
[[0.4375     1.         0.66666667 ... 1.         0.         0.66666667]
 [0.27083333 1.         1.         ... 1.         0.5        0.66666667]
 [0.10416667 0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.45833333 0.         0.66666667 ... 1.         0.         0.66666667]
 [0.33333333 0.         0.33333333 ... 0.5        0.         0.66666667]
 [0.75       1.         0.         ... 1.         0.         1.        ]]
104    1
100    1
125    1
69     1
83     1
      ..
29     1
292    0
140    1
94     1
31     1
Name: target, Length: 152, dtype: int64
Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')
0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64
0      1
1      1
2      0
3      1
4      0
      ..
298    0
299    1
300    1
301    1
302    0
Name: sex, Length: 303, dtype: int64
0      3
1      2
2      1
3      1
4      0
      ..
298    0
299    3
300    0
301    0
302    1
Name: cp, Length: 303, dtype: int64
0      145
1      130
2      130
3      120
4      120
      ...
298    140
299    110
300    144
301    130
302    130
Name: trestbps, Length: 303, dtype: int64
0      233
1      250
2      204
3      236
4      354
      ...
298    241
299    264
300    193
301    131
302    236
Name: chol, Length: 303, dtype: int64
0      1
1      0
2      0
3      0
4      0
      ..
298    0
299    0
300    1
301    0
302    0
Name: fbs, Length: 303, dtype: int64
0      0
1      1
2      0
3      1
4      1
      ..
298    1
299    1
300    1
301    1
302    0
Name: restecg, Length: 303, dtype: int64
0      150
1      187
2      172
3      178
4      163
      ...
298    123
299    132
300    141
301    115
302    174
Name: thalach, Length: 303, dtype: int64
0      0
1      0
2      0
3      0
4      1
      ..
298    1
299    0
300    0
301    1
302    0
Name: exang, Length: 303, dtype: int64
0      2.3
1      3.5
2      1.4
3      0.8
4      0.6
      ...
298    0.2
299    1.2
300    3.4
301    1.2
302    0.0
Name: oldpeak, Length: 303, dtype: float64
0      0
1      0
2      2
3      2
4      2
      ..
298    1
299    1
300    1
301    1
302    1
Name: slope, Length: 303, dtype: int64
0      0
1      0
2      0
3      0
4      0
      ..
298    0
299    0
300    2
301    1
302    1
Name: ca, Length: 303, dtype: int64
0      1
1      2
2      2
3      2
4      2
      ..
298    3
299    3
300    3
301    3
302    2
Name: thal, Length: 303, dtype: int64
0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [22]:
import random
import numpy as np

x1 = a['age']
x2 = a['sex']
x3 = a['cp']
x4 = a['trestbps']
x5 = a['chol']
x6 = a['fbs']
x7 = a['restecg']
x8 = a['thalach']
x9 = a['exang']
x10 = a['oldpeak']
x11 = a['slope']
x12 = a['ca']
x13 = a['thal']
y_p = []

def perceptron(w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, b):
    for i in range(len(x1)):
        z = x1[i] * w1 + x2[i] * w2 + x3[i] * w3 + x4[i] * w4 + x5[i] * w5 + x6[i] * w6 + x7[i] * w7 + x8[i] * w8 + x9[i] * w9 + x10[i] * w10 + x11[i] * w11 + x12[i] * w12 + x13[i] * w13 + b
        s = 1 / (1 + np.exp(-z))
        if s >= 0.5:
            y_p.append(1)
        else:
            y_p.append(0)
    print(y_p)

w1 = random.randint(1, 100)
w2 = random.randint(1, 100)
w3 = random.randint(1, 100)
w4 = random.randint(1, 100)
w5 = random.randint(1, 100)
w6 = random.randint(1, 100)
w7 = random.randint(1, 100)
w8 = random.randint(1, 100)
w9 = random.randint(1, 100)
w10 = random.randint(1, 100)
w11 = random.randint(1, 100)
w12 = random.randint(1, 100)
w13 = random.randint(1, 100)
perceptron(w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, 1)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [28]:

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import random as rd
a = pd.read_csv('/content/heart.csv')
x = a.drop("target", axis=1)
y = a["target"]
scaler = MinMaxScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)
f = x_train.shape[1]
w = []
for _ in range(f):
    weight = rd.random()
    w.append(weight)
bias = rd.random()
def perceptron(x):
    z = (
        x[0] * w[0] +
        x[1] * w[1] +
        x[2] * w[2] +
        x[3] * w[3] +
        x[4] * w[4] +
        x[5] * w[5] +
        x[6] * w[6] +
        x[7] * w[7] +
        x[8] * w[8] +
        x[9] * w[9] +
        x[10] * w[10] +
        x[11] * w[11] +
        x[12] * w[12] +
        bias
    )
    return 1 / (1 + np.exp(-z))
y_p = []
for x in x_train:
    if perceptron(x) >= 0.5:
        y_p.append(1)
    else:
        y_p.append(0)

current_p = np.sum(y_p == y_train)
acc = current_p / len(y_train)
print(f'Accuracy: {acc:.2f}')

Accuracy: 0.55